- name: install apache
  become: yes
  yum:
    name: httpd
    state: present

- name: change apache to specified port
  become: yes
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: 'Listen {{web_port}}'

- name: turn off isolated nodes if the webserver happens to be tower
  uri:
    url: "https://{{ansible_host}}/api/v2/settings/jobs/"
    user: "{{tower_user}}"
    password: "{{tower_pass}}"
    method: PATCH
    validate_certs: False
    force_basic_auth: yes
    body_format: json
    body: ' {"AWX_PROOT_ENABLED": false}'
    status_code:
      - 200
  when: lookup('env','USER') == 'awx'

- name: start httpd
  become: yes
  service:
    name: httpd
    state: started

- name: create HTML report
  become: yes
  template:
    src: report.j2
    dest: "{{ file_path }}"

- name: display link to inventory report
  debug:
    msg: "Please go to http://{{hostvars[web_host].ansible_host}} + ':' + {{web_port}}"
