- name: install apache
  become: yes
  yum:
    name: httpd
    state: present

- name: start httpd
  become: yes
  service:
    name: httpd
    state: started

- name: create HTML report
  become: yes
  template:
    src: report.j2
    dest: "{{ file_path }}"

- name: display link to inventory report
  debug:
    msg: "Please go to http://{{hostvars[web_host].ansible_host}} + ':' + {{web_port}}"
