---
# THIS PLAYBOOK MUST BE RUN FROM CLI
# PLEASE RUN WITH ANSIBLE-PLAYBOOK COMMAND
# ansible-playbook setup.yml
- name: SETUP NETWORK JOBS IN TOWER
  hosts: routers
  connection: local
  gather_facts: no
  tasks:
    - name: CREATE INVENTORY
      tower_inventory:
        name: "Workshop Inventory"
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
      run_once: true
      delegate_to: localhost

    - name: ADD ANSIBLE HOST INTO TOWER
      tower_host:
        name: "{{ inventory_hostname }}"
        inventory: "Workshop Inventory"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        variables:
          ansible_host: "{{ansible_host}}"
          ansible_user: "{{ansible_user}}"
          private_ip: "{{private_ip}}"
      run_once: true
      delegate_to: localhost

    - name: ADD NETWORK HOSTS INTO TOWER
      tower_host:
        name: "{{ inventory_hostname }}"
        inventory: "Workshop Inventory"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        variables:
          ansible_network_os: "{{ansible_network_os}}"
          ansible_host: "{{ansible_host}}"
          ansible_user: "{{ansible_user}}"
          private_ip: "{{private_ip}}"

    - name: ADD CREDENTIAL INTO TOWER
      tower_credential:
        name: Workshop Credential
        ssh_key_data: "/home/{{ansible_user}}/.ssh/aws-private.pem"
        kind: ssh
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
      run_once: true
      delegate_to: localhost

    - name: ADD REPO INTO TOWER
      tower_project:
        name: "Workshop Project"
        organization: "Default"
        scm_type: git
        scm_url: "https://github.com/network-automation/tower_workshop"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
      run_once: true
      delegate_to: localhost

    - name: REMOVE DEMO JOB TEMPLATE
      tower_job_template:
        name: "Demo Job Template"
        job_type: "run"
        project: "Demo Project"
        state: absent
        playbook: "null"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
      run_once: true
      delegate_to: localhost

    - name: CREATE BACKUP JOB TEMPLATE
      tower_job_template:
        name: "BACKUP NETWORK CONFIG"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_backup.yml"
        credential: "Workshop Credential"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
      run_once: true
      delegate_to: localhost

    - name: FIND BACKUPS
      find:
        paths: /tmp/backup
        file_type: directory
      register: backups
      run_once: true
      delegate_to: localhost

    - name: CREATE RESTORE JOB TEMPLATE
      tower_job_template:
        name: "RESTORE NETWORK CONFIG"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_restore.yml"
        credential: "Workshop Credential"
        survey_enabled: true
        survey_spec: "{{ lookup('template', '{{playbook_dir}}/templates/backup.j2') }}"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
