---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: BACKUP CONFIGURATION
      include_role:
        name: "{{ansible_network_os}}"
        tasks_from: backup.yml
