---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: all
  gather_facts: no

  tasks:
    - name: BACKUP CONFIGURATION
      include_role:
        name: "{{ansible_network_os}}"
        tasks_from: backup.yml

    # This verifies the backup directory exists on the host you want to store conifgs
    - name: CREATE DIRECTORY ON {{store_configs}}
      vars:
        ansible_connection: ssh
      file:
        path: /tmp/backup
        state: directory
      delegate_to: "{{store_configs}}"

    # This is required because you might be running a Tower cluster, so we want the configs to all be in one place
    - name: TRANSFER FILE FROM THIS ANSIBLE HOST TO {{store_cofigs}}
      vars:
        backup_filename: "{{config_output.backup_path.split('/')[-1]}}"
        ansible_connection: ssh
      copy:
        src: "{{config_output.backup_path}}"
        dest: "/backup/{{backup_filename}}"
      delegate_to: "{{store_configs}}"
