---
- name: configure l3 interface
  hosts: routers
  gather_facts: no

  tasks:

    - name: load l3 interface role
      import_role:
        name: read_interfaces

    - name: print l3 interface role
      debug:
        msg:
        - "Interface info for {{inventory_hostname}}"
        - "{{interfaces_info}}"
