---
- name: CONFIGURE SYSTEM PROPERTIRES
  hosts: all
  gather_facts: no

  tasks:
    - name: BACKUP CONFIGURATION
      include_role:
        name: "{{ansible_network_os}}"
        tasks_from: user.yml
      when: ansible_network_os is defined
