---
- name: SET ROUTER BANNERS
  hosts: all
  gather_facts: no

  tasks:

    - name: LOAD BANNER ONTO NETWORK DEVICE
      net_banner:
        banner: login
        text: |
          "{{network_banner}}"
      when: ansible_network_os is defined
