---
- name: GATHER INFORMATION FROM ROUTERS
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: SHOW COMMAND
      include_role:
        name: "{{ansible_network_os}}"
        tasks_from: show_commands.yml
      when: ansible_network_os is defined
