---
- name: configure l3 interface
  hosts: routers
  gather_facts: no

  tasks:
    - name: load read interfaces role
      include_role:
        name: read_interfaces

    - name: print l3 interface role
      debug:
        msg:
        - "Interface info for {{inventory_hostname}}"
        - "{{ansible_network_resources.interfaces}}"
