- name: BACKUP THE CONFIG
  ios_config:
    backup: yes
  register: config_output

- name: REMOVE NON CONFIG LINES - REGEXP
  lineinfile:
    path: "{{config_output.backup_path}}"
    regexp: 'Current configuration.*'
    state: absent
