- debug:
    msg: "restoring from /tmp/backup/{{rollback_date}}/{{inventory_hostname}}"
- name: RESTORE THE CONFIG
  ios_config:
    replace: block
    src: "/tmp/backup/{{rollback_date}}/{{inventory_hostname}}"
  register: config_output
