- name: BACKUP THE CONFIG
  junos_config:
    backup: yes
  register: config_output

- name: RENAME BACKUP
  copy:
    src: "{{config_output.backup_path}}"
    dest: "{{playbook_dir}}/backup/{{inventory_hostname}}.config"
