---
- name: gather juniper junos facts
  collections:
    - junipernetworks.junos
  vars:
    ansible_connection: netconf
  junipernetworks.junos.facts:
    gather_subset: config
    gather_network_resources: "{{ network_resource | default('all') }}"
